# Generated by Django 3.0.3 on 2020-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correlations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experimentName', models.CharField(max_length=100)),
                ('rowNum', models.PositiveIntegerField()),
                ('colNum', models.PositiveIntegerField()),
                ('rowLabel', models.CharField(max_length=100)),
                ('colLabel', models.CharField(max_length=100)),
                ('corrValue', models.FloatField()),
            ],
            options={
                'ordering': ('experimentName',),
            },
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('species', models.TextField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
